// GENERATED CODE - DO NOT MODIFY BY HAND
// Run: flutter pub run build_runner build

part of 'database.dart';

// ─── This file is generated by drift_dev ─────────────────────────────────────
// After adding the dependency and running build_runner, this will be replaced
// with actual generated code. The stub below allows the project to compile
// during initial setup before code generation is run.

// To generate: flutter pub run build_runner build --delete-conflicting-outputs

class $ActivityLogsTable extends ActivityLogs
    with TableInfo<$ActivityLogsTable, ActivityLog> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $ActivityLogsTable(this.attachedDatabase, [this._alias]);

  static const VerificationMeta _idMeta = const VerificationMeta('id');
  @override
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
      'id', aliasedName, false,
      hasAutoIncrement: true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      defaultConstraints:
          GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));

  static const VerificationMeta _logIdMeta =
      const VerificationMeta('logId');
  @override
  late final GeneratedColumn<String> logId = GeneratedColumn<String>(
      'log_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      defaultConstraints: GeneratedColumn.constraintIsAlways('UNIQUE'));

  static const VerificationMeta _dateMeta =
      const VerificationMeta('date');
  @override
  late final GeneratedColumn<String> date = GeneratedColumn<String>(
      'date', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);

  static const VerificationMeta _durationMinutesMeta =
      const VerificationMeta('durationMinutes');
  @override
  late final GeneratedColumn<int> durationMinutes = GeneratedColumn<int>(
      'duration_minutes', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      defaultValue: const Constant(0));

  static const VerificationMeta _exerciseTypesMeta =
      const VerificationMeta('exerciseTypes');
  @override
  late final GeneratedColumn<String> exerciseTypes =
      GeneratedColumn<String>('exercise_types', aliasedName, false,
          type: DriftSqlType.string,
          requiredDuringInsert: false,
          defaultValue: const Constant(''));

  static const VerificationMeta _moodMeta =
      const VerificationMeta('mood');
  @override
  late final GeneratedColumn<String> mood = GeneratedColumn<String>(
      'mood', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);

  static const VerificationMeta _selfTagArchetypeMeta =
      const VerificationMeta('selfTagArchetype');
  @override
  late final GeneratedColumn<String> selfTagArchetype =
      GeneratedColumn<String>('self_tag_archetype', aliasedName, false,
          type: DriftSqlType.string, requiredDuringInsert: true);

  static const VerificationMeta _notesMeta =
      const VerificationMeta('notes');
  @override
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
      'notes', aliasedName, true,
      type: DriftSqlType.string, requiredDuringInsert: false);

  static const VerificationMeta _tagsMeta =
      const VerificationMeta('tags');
  @override
  late final GeneratedColumn<String> tags = GeneratedColumn<String>(
      'tags', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      defaultValue: const Constant(''));

  static const VerificationMeta _memeCreatedMeta =
      const VerificationMeta('memeCreated');
  @override
  late final GeneratedColumn<bool> memeCreated = GeneratedColumn<bool>(
      'meme_created', aliasedName, false,
      type: DriftSqlType.bool,
      requiredDuringInsert: false,
      defaultValue: const Constant(false));

  static const VerificationMeta _memeIdMeta =
      const VerificationMeta('memeId');
  @override
  late final GeneratedColumn<String> memeId = GeneratedColumn<String>(
      'meme_id', aliasedName, true,
      type: DriftSqlType.string, requiredDuringInsert: false);

  @override
  List<GeneratedColumn> get $columns => [
        id,
        logId,
        date,
        durationMinutes,
        exerciseTypes,
        mood,
        selfTagArchetype,
        notes,
        tags,
        memeCreated,
        memeId
      ];

  @override
  String get aliasedName => _alias ?? actualTableName;

  @override
  String get actualTableName => $name;

  static const String $name = 'activity_logs';

  @override
  VerificationContext validateIntegrity(
      Insertable<ActivityLog> instance,
      {bool isInserting = false}) {
    final context = VerificationContext();
    final data = instance.toColumns(true);
    if (data.containsKey('id')) {
      context.handle(_idMeta,
          id.isAcceptableOrUnknown(data['id']!, _idMeta));
    }
    if (data.containsKey('log_id')) {
      context.handle(_logIdMeta,
          logId.isAcceptableOrUnknown(data['log_id']!, _logIdMeta));
    } else if (isInserting) {
      context.missing(_logIdMeta);
    }
    if (data.containsKey('date')) {
      context.handle(_dateMeta,
          date.isAcceptableOrUnknown(data['date']!, _dateMeta));
    } else if (isInserting) {
      context.missing(_dateMeta);
    }
    if (data.containsKey('duration_minutes')) {
      context.handle(
          _durationMinutesMeta,
          durationMinutes.isAcceptableOrUnknown(
              data['duration_minutes']!, _durationMinutesMeta));
    }
    if (data.containsKey('exercise_types')) {
      context.handle(
          _exerciseTypesMeta,
          exerciseTypes.isAcceptableOrUnknown(
              data['exercise_types']!, _exerciseTypesMeta));
    }
    if (data.containsKey('mood')) {
      context.handle(_moodMeta,
          mood.isAcceptableOrUnknown(data['mood']!, _moodMeta));
    } else if (isInserting) {
      context.missing(_moodMeta);
    }
    if (data.containsKey('self_tag_archetype')) {
      context.handle(
          _selfTagArchetypeMeta,
          selfTagArchetype.isAcceptableOrUnknown(
              data['self_tag_archetype']!, _selfTagArchetypeMeta));
    } else if (isInserting) {
      context.missing(_selfTagArchetypeMeta);
    }
    return context;
  }

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  ActivityLog map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix =
        tablePrefix != null ? '$tablePrefix.' : '';
    return ActivityLog(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}id'])!,
      logId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}log_id'])!,
      date: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}date'])!,
      durationMinutes: attachedDatabase.typeMapping.read(
          DriftSqlType.int,
          data['${effectivePrefix}duration_minutes'])!,
      exerciseTypes: attachedDatabase.typeMapping.read(
          DriftSqlType.string,
          data['${effectivePrefix}exercise_types'])!,
      mood: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}mood'])!,
      selfTagArchetype: attachedDatabase.typeMapping.read(
          DriftSqlType.string,
          data['${effectivePrefix}self_tag_archetype'])!,
      notes: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}notes']),
      tags: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}tags'])!,
      memeCreated: attachedDatabase.typeMapping
          .read(DriftSqlType.bool, data['${effectivePrefix}meme_created'])!,
      memeId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}meme_id']),
    );
  }

  @override
  $ActivityLogsTable createAlias(String alias) =>
      $ActivityLogsTable(attachedDatabase, alias);
}

class ActivityLog extends DataClass
    implements Insertable<ActivityLog> {
  final int id;
  final String logId;
  final String date;
  final int durationMinutes;
  final String exerciseTypes;
  final String mood;
  final String selfTagArchetype;
  final String? notes;
  final String tags;
  final bool memeCreated;
  final String? memeId;

  const ActivityLog({
    required this.id,
    required this.logId,
    required this.date,
    required this.durationMinutes,
    required this.exerciseTypes,
    required this.mood,
    required this.selfTagArchetype,
    this.notes,
    required this.tags,
    required this.memeCreated,
    this.memeId,
  });

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['log_id'] = Variable<String>(logId);
    map['date'] = Variable<String>(date);
    map['duration_minutes'] = Variable<int>(durationMinutes);
    map['exercise_types'] = Variable<String>(exerciseTypes);
    map['mood'] = Variable<String>(mood);
    map['self_tag_archetype'] = Variable<String>(selfTagArchetype);
    if (!nullToAbsent || notes != null) {
      map['notes'] = Variable<String>(notes);
    }
    map['tags'] = Variable<String>(tags);
    map['meme_created'] = Variable<bool>(memeCreated);
    if (!nullToAbsent || memeId != null) {
      map['meme_id'] = Variable<String>(memeId);
    }
    return map;
  }

  ActivityLogsCompanion toCompanion(bool nullToAbsent) {
    return ActivityLogsCompanion(
      id: Value(id),
      logId: Value(logId),
      date: Value(date),
      durationMinutes: Value(durationMinutes),
      exerciseTypes: Value(exerciseTypes),
      mood: Value(mood),
      selfTagArchetype: Value(selfTagArchetype),
      notes: notes == null && nullToAbsent
          ? const Value.absent()
          : Value(notes),
      tags: Value(tags),
      memeCreated: Value(memeCreated),
      memeId: memeId == null && nullToAbsent
          ? const Value.absent()
          : Value(memeId),
    );
  }

  @override
  String toString() => 'ActivityLog(id: $id, logId: $logId, date: $date, '
      'mood: $mood, archetype: $selfTagArchetype)';

  @override
  bool operator ==(Object other) =>
      other is ActivityLog && other.id == id;

  @override
  int get hashCode => id.hashCode;
}

class ActivityLogsCompanion extends UpdateCompanion<ActivityLog> {
  final Value<int> id;
  final Value<String> logId;
  final Value<String> date;
  final Value<int> durationMinutes;
  final Value<String> exerciseTypes;
  final Value<String> mood;
  final Value<String> selfTagArchetype;
  final Value<String?> notes;
  final Value<String> tags;
  final Value<bool> memeCreated;
  final Value<String?> memeId;
  final Value<int> rowid;

  const ActivityLogsCompanion({
    this.id = const Value.absent(),
    this.logId = const Value.absent(),
    this.date = const Value.absent(),
    this.durationMinutes = const Value.absent(),
    this.exerciseTypes = const Value.absent(),
    this.mood = const Value.absent(),
    this.selfTagArchetype = const Value.absent(),
    this.notes = const Value.absent(),
    this.tags = const Value.absent(),
    this.memeCreated = const Value.absent(),
    this.memeId = const Value.absent(),
    this.rowid = const Value.absent(),
  });

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (logId.present) map['log_id'] = Variable<String>(logId.value);
    if (date.present) map['date'] = Variable<String>(date.value);
    if (durationMinutes.present)
      map['duration_minutes'] =
          Variable<int>(durationMinutes.value);
    if (exerciseTypes.present)
      map['exercise_types'] =
          Variable<String>(exerciseTypes.value);
    if (mood.present) map['mood'] = Variable<String>(mood.value);
    if (selfTagArchetype.present)
      map['self_tag_archetype'] =
          Variable<String>(selfTagArchetype.value);
    if (notes.present) map['notes'] = Variable<String>(notes.value);
    if (tags.present) map['tags'] = Variable<String>(tags.value);
    if (memeCreated.present)
      map['meme_created'] = Variable<bool>(memeCreated.value);
    if (memeId.present) map['meme_id'] = Variable<String>(memeId.value);
    return map;
  }

  @override
  String toString() => 'ActivityLogsCompanion(logId: $logId, date: $date)';
}

// ─── LocalMemes table ─────────────────────────────────────────────────────────

class $LocalMemesTable extends LocalMemes
    with TableInfo<$LocalMemesTable, LocalMeme> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $LocalMemesTable(this.attachedDatabase, [this._alias]);

  late final GeneratedColumn<int> id = GeneratedColumn<int>(
      'id', aliasedName, false,
      hasAutoIncrement: true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      defaultConstraints:
          GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));

  late final GeneratedColumn<String> memeId = GeneratedColumn<String>(
      'meme_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      defaultConstraints: GeneratedColumn.constraintIsAlways('UNIQUE'));

  late final GeneratedColumn<String> localImagePath =
      GeneratedColumn<String>('local_image_path', aliasedName, false,
          type: DriftSqlType.string, requiredDuringInsert: true);

  late final GeneratedColumn<String> captions =
      GeneratedColumn<String>('captions', aliasedName, false,
          type: DriftSqlType.string,
          requiredDuringInsert: false,
          defaultValue: const Constant(''));

  late final GeneratedColumn<String> tags = GeneratedColumn<String>(
      'tags', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      defaultValue: const Constant(''));

  late final GeneratedColumn<String> archetypeTag =
      GeneratedColumn<String>('archetype_tag', aliasedName, true,
          type: DriftSqlType.string, requiredDuringInsert: false);

  late final GeneratedColumn<bool> isUploaded = GeneratedColumn<bool>(
      'is_uploaded', aliasedName, false,
      type: DriftSqlType.bool,
      requiredDuringInsert: false,
      defaultValue: const Constant(false));

  late final GeneratedColumn<String> remoteUrl =
      GeneratedColumn<String>('remote_url', aliasedName, true,
          type: DriftSqlType.string, requiredDuringInsert: false);

  late final GeneratedColumn<String> createdAt =
      GeneratedColumn<String>('created_at', aliasedName, false,
          type: DriftSqlType.string, requiredDuringInsert: true);

  @override
  List<GeneratedColumn> get $columns => [
        id,
        memeId,
        localImagePath,
        captions,
        tags,
        archetypeTag,
        isUploaded,
        remoteUrl,
        createdAt
      ];

  @override
  String get aliasedName => _alias ?? actualTableName;

  @override
  String get actualTableName => $name;

  static const String $name = 'local_memes';

  @override
  VerificationContext validateIntegrity(
      Insertable<LocalMeme> instance,
      {bool isInserting = false}) {
    return VerificationContext();
  }

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  LocalMeme map(Map<String, dynamic> data, {String? tablePrefix}) {
    final p = tablePrefix != null ? '$tablePrefix.' : '';
    return LocalMeme(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${p}id'])!,
      memeId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${p}meme_id'])!,
      localImagePath: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${p}local_image_path'])!,
      captions: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${p}captions'])!,
      tags: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${p}tags'])!,
      archetypeTag: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${p}archetype_tag']),
      isUploaded: attachedDatabase.typeMapping
          .read(DriftSqlType.bool, data['${p}is_uploaded'])!,
      remoteUrl: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${p}remote_url']),
      createdAt: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${p}created_at'])!,
    );
  }

  @override
  $LocalMemesTable createAlias(String alias) =>
      $LocalMemesTable(attachedDatabase, alias);
}

class LocalMeme extends DataClass implements Insertable<LocalMeme> {
  final int id;
  final String memeId;
  final String localImagePath;
  final String captions;
  final String tags;
  final String? archetypeTag;
  final bool isUploaded;
  final String? remoteUrl;
  final String createdAt;

  const LocalMeme({
    required this.id,
    required this.memeId,
    required this.localImagePath,
    required this.captions,
    required this.tags,
    this.archetypeTag,
    required this.isUploaded,
    this.remoteUrl,
    required this.createdAt,
  });

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['meme_id'] = Variable<String>(memeId);
    map['local_image_path'] = Variable<String>(localImagePath);
    map['captions'] = Variable<String>(captions);
    map['tags'] = Variable<String>(tags);
    if (!nullToAbsent || archetypeTag != null)
      map['archetype_tag'] = Variable<String>(archetypeTag);
    map['is_uploaded'] = Variable<bool>(isUploaded);
    if (!nullToAbsent || remoteUrl != null)
      map['remote_url'] = Variable<String>(remoteUrl);
    map['created_at'] = Variable<String>(createdAt);
    return map;
  }

  LocalMemesCompanion toCompanion(bool nullToAbsent) =>
      LocalMemesCompanion(
        id: Value(id),
        memeId: Value(memeId),
        localImagePath: Value(localImagePath),
        captions: Value(captions),
        tags: Value(tags),
        archetypeTag: archetypeTag == null && nullToAbsent
            ? const Value.absent()
            : Value(archetypeTag),
        isUploaded: Value(isUploaded),
        remoteUrl: remoteUrl == null && nullToAbsent
            ? const Value.absent()
            : Value(remoteUrl),
        createdAt: Value(createdAt),
      );

  @override
  bool operator ==(Object other) =>
      other is LocalMeme && other.id == id;

  @override
  int get hashCode => id.hashCode;
}

class LocalMemesCompanion extends UpdateCompanion<LocalMeme> {
  final Value<int> id;
  final Value<String> memeId;
  final Value<String> localImagePath;
  final Value<String> captions;
  final Value<String> tags;
  final Value<String?> archetypeTag;
  final Value<bool> isUploaded;
  final Value<String?> remoteUrl;
  final Value<String> createdAt;
  final Value<int> rowid;

  const LocalMemesCompanion({
    this.id = const Value.absent(),
    this.memeId = const Value.absent(),
    this.localImagePath = const Value.absent(),
    this.captions = const Value.absent(),
    this.tags = const Value.absent(),
    this.archetypeTag = const Value.absent(),
    this.isUploaded = const Value.absent(),
    this.remoteUrl = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (memeId.present) map['meme_id'] = Variable<String>(memeId.value);
    if (localImagePath.present)
      map['local_image_path'] =
          Variable<String>(localImagePath.value);
    if (captions.present)
      map['captions'] = Variable<String>(captions.value);
    if (tags.present) map['tags'] = Variable<String>(tags.value);
    if (archetypeTag.present)
      map['archetype_tag'] = Variable<String>(archetypeTag.value);
    if (isUploaded.present)
      map['is_uploaded'] = Variable<bool>(isUploaded.value);
    if (remoteUrl.present)
      map['remote_url'] = Variable<String>(remoteUrl.value);
    if (createdAt.present)
      map['created_at'] = Variable<String>(createdAt.value);
    return map;
  }

  @override
  String toString() => 'LocalMemesCompanion(memeId: $memeId)';
}

// ─── Database implementation ──────────────────────────────────────────────────

abstract class _$AppDatabase extends GeneratedDatabase {
  _$AppDatabase(QueryExecutor e) : super(e);

  late final $ActivityLogsTable activityLogs =
      $ActivityLogsTable(this);
  late final $LocalMemesTable localMemes = $LocalMemesTable(this);

  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();

  @override
  List<DatabaseSchemaEntity> get allSchemaEntities =>
      [activityLogs, localMemes];
}
